package com.example.giaphong.mapper;

import com.example.giaphong.Entities.TaskEntityJPA;
import com.example.giaphong.model.TaskEntity;

import com.example.giaphong.model.TaskEntityExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface TaskEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	long countByExample(TaskEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int deleteByExample(TaskEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int insert(TaskEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int insertSelective(TaskEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	List<TaskEntity> selectByExampleWithBLOBs(TaskEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	List<TaskEntity> selectByExample(TaskEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	TaskEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") TaskEntity row, @Param("example") TaskEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int updateByExampleWithBLOBs(@Param("row") TaskEntity row, @Param("example") TaskEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int updateByExample(@Param("row") TaskEntity row, @Param("example") TaskEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int updateByPrimaryKeySelective(TaskEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int updateByPrimaryKeyWithBLOBs(TaskEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_tasks
	 * @mbg.generated  Mon Aug 01 20:52:49 ICT 2022
	 */
	int updateByPrimaryKey(TaskEntity row);


	TaskEntity updateByExample(TaskEntity task);

	List<Map<String,Object>> findAll();
}