package com.example.giaphong.mapper;

import com.example.giaphong.model.UserEntity;
import com.example.giaphong.model.UserEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	long countByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	int deleteByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	int insert(UserEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	int insertSelective(UserEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	List<UserEntity> selectByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	UserEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") UserEntity row, @Param("example") UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	int updateByExample(@Param("row") UserEntity row, @Param("example") UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	int updateByPrimaryKeySelective(UserEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_users
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	int updateByPrimaryKey(UserEntity row);
}