package com.example.giaphong.model;

import java.util.Date;

public class UserEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.id
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.username
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.password
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.email
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.created_date
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.updated_date
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private Date updatedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.created_by
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.updated_by
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private Integer updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.status
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.avatar
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_users.is_enabled
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	private Boolean isEnabled;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.id
	 * @return  the value of tbl_users.id
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.id
	 * @param id  the value for tbl_users.id
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.username
	 * @return  the value of tbl_users.username
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.username
	 * @param username  the value for tbl_users.username
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.password
	 * @return  the value of tbl_users.password
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.password
	 * @param password  the value for tbl_users.password
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.email
	 * @return  the value of tbl_users.email
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.email
	 * @param email  the value for tbl_users.email
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.created_date
	 * @return  the value of tbl_users.created_date
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.created_date
	 * @param createdDate  the value for tbl_users.created_date
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.updated_date
	 * @return  the value of tbl_users.updated_date
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.updated_date
	 * @param updatedDate  the value for tbl_users.updated_date
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.created_by
	 * @return  the value of tbl_users.created_by
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.created_by
	 * @param createdBy  the value for tbl_users.created_by
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.updated_by
	 * @return  the value of tbl_users.updated_by
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.updated_by
	 * @param updatedBy  the value for tbl_users.updated_by
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.status
	 * @return  the value of tbl_users.status
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.status
	 * @param status  the value for tbl_users.status
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.avatar
	 * @return  the value of tbl_users.avatar
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.avatar
	 * @param avatar  the value for tbl_users.avatar
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_users.is_enabled
	 * @return  the value of tbl_users.is_enabled
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public Boolean getIsEnabled() {
		return isEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_users.is_enabled
	 * @param isEnabled  the value for tbl_users.is_enabled
	 * @mbg.generated  Mon Aug 01 22:29:41 ICT 2022
	 */
	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}
}